POST http://localhost:8080/api/shows/f6838752-12db-441d-b648-77df9ec3f899/seasons HTTP/1.1
Content-Type: application/json

{
    "title": "Season 02",
    "releaseDate": "2025-04-01",
    "description": "asdaadfsfsdfasdfasfasdfsdf"
}