POST http://localhost:8080/api/seasons/312adf34-1cf6-4e8f-ba83-53eb5a26a060/episodes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJaaW1sZXdpcyIsImlhdCI6MTc1MjgxMTg3NiwiZXhwIjoxNzUzNDE2Njc2fQ.Q-lRFyl6TqPndOl0eezM6LATN0ewFhwROFLvvK13G2peO043sDvED3zL5VUKUppWarf6-JZeLjxznstENtRcZw

{
  "title": "Tập 6",
  "number": "06",
  "description": "Tập 6 bộ season 5",
  "url": "aTYg6tKGxHbQ12513XWkL02EtwOYQFV8PG7sBBGs52Xg",
  "releaseDate": "2025-05-26",
  "duration": 500,
  "openingStart": 100,
  "openingEnd": 100
}