POST http://localhost:8080/api/orders/confirm HTTP/1.1
Content-Type: application/json

{
  "gateway": "BIDV",
  "transactionDate": "2025-06-24 14:14:47",
  "accountNumber": "8865595094",
  "subAccount": "962477K8RC",
  "code": "GD74717012",
  "content": "id: GD26649385",
  "transferType": "in",
  "description": "BankAPINotify id: 9717A694-532F-4AD9-A049-EF2E9E5FFDF7",
  "transferAmount": 10000,
  "referenceCode": "c9c4d64d-0db1-47e3-8525-3a1a711817f4",
  "accumulated": 0,
  "id": 15726785
}