DELETE http://localhost:8080/api/seasons/3be08083-7160-4b84-b609-bbdb24ee5b88 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJaaW1sZXdpcyIsImlhdCI6MTc1MDc3OTg2MiwiZXhwIjoxNzUxMzg0NjYyfQ.HjSiv_iLYJT-bTLvCygT2jVDvK6njUqyk9LT0R-_FNflUvccWDbhSX0gkXvZ7EAuXvaQz2VS1TjSFUkPbtDc6Q