PUT http://localhost:8080/api/episodes/8ce1d77d-3db4-4d10-9987-b3767125e395 HTTP/1.1
Content-Type: application/json

{
    "title": "mnbvcxz",
    "number": "666",
    "description": "v",
    "url": "aasdqwasdasdas",
    "releaseDate": "2001-09-11",
    "duration": 1000000,
    "openingStart": 290,
    "openingEnd": 400,
    "view": 3
}